// Cintasign users (from Cinta.txt)
export const CINTASIGN_USERS = [
  "JASON WADE MENNELL",
  "NATALIE TAMRYN CROUCH",
  "RAEESA KADIR",
  "SBONGAMANDLA MNGUNI",
  "AYANDA MASIKANE",
  "MAWANDE MDUNJANA",
  "CORNE SCHALK DORFLING",
  "MBUSO MNGUNI",
  "JOHN DLAMINI",
  "SBONGESENI LUCKY NKOSI",
  "MUSAWENKOSI MYENI",
  "KHEDASI PATRICK MLAMBO",
  "SIYABONGA KHUMALO",
  "DUMEZWENI MBELE",
  "LINDANI DUBE",
  "SONOSAKHE NGUBANE",
  "SIFISO MCHUNU",
  "BONGIWE NKOMO",
  "BONG'MUSA NGUBO",
  "SIZWE MKHIZE",
  "RICHARD MKWAE",
  "SIYABONGA SPHAMANDLA NTSELE",
  "SIGWATA JOHN YENDE",
  "MXOLISI EMMANUEL SIBISI",
  "SAMSON MBONGENI NGWENYA",
  "SAMSON NDLOVU",
  "LUNGISANI PIUS MDLADLA",
  "THUBALETHIU SIMON MATHENJWA",
  "BHEKI - DINGUMUZI MKHUMBUZI",
  "MDUDUZI ERIC PHUNGULA",
  "NKOSINATHI THONGO BHENGU",
  "GUGU PRINCESS MTOLO",
  "MBUYISWA EMMANUEL NDLOVU",
  "BUSISIWE GOODNESS KUNENE",
  "THULANI ISAAC THOMO",
  "PHUMLANI SIPHO MAKHAYE",
  "TREVOR FANOZI MAGAGULA",
  "MDUDUZI WILLIAM NXUMALO",
  "THULANI TERRANCE MTHETHWA",
  "BONGANI BHENGU",
  "NOMUSA MARY-JANE BUTHELEZI",
  "SABELO GWEBU",
  "LONDIWE HADEBE",
  "SBUSISO WISEMAN KHOZA",
  "NKOSINATHI MICHAEL MKHONTO",
  "NKOSIPHANA AMEN MNGADI",
  "ZODWA NGCOBO",
  "ANDILE CYRIL NDLOVU",
  "MDUDUZI SITHOLE",
  "MZWAKHE GIFT NDWANDWE",
  "S'BUSISO BLESSIING THWALA",
  "ZWELIHLE NGEMA",
  "PHIWAYINKOSI ZAKHELE MTHEMBU",
  "BONGANI DESMOND MOTSOUNYANE",
  "BHEKIZENZO JOHANNES ZONDI",
  "LUCAS SIBUSISO MATHONSI",
  "NHLANHALA LINDA",
  "SONNYBOY MKHALIPHI",
  "SIKELELA JERMIA MKHUMBUZA",
  "MLUNGISI PETROS MAHLABA",
  "SABELO AYANDA VILANE",
  "MANDLA GIDION DLAMINI",
  "SKHUMBUZO KHUMBULANI MBUYAZI",
  "CLEMENT DLAMINI",
  "THOKOZANI MANDLA MYENI",
  "SIFISO REGGIE NENE"
] as const;

// Ringomode DSP users
export const RINGOMODE_USERS = [
  "Praiselord Ndlovu",
  "Thembisile Ndlovu",
  "Precilla Seeparsad",
  "Msawakhe Zuma",
  "Themba Gumede",
  "Nkosinathi Mtembu",
  "Mbongeleni Mtshali",
  "Vusi Mtshali",
  "Themba Khumalo",
  "Sibongiseni Thwala",
  "Thembinkosi Dlamini",
  "Zodwa Tembe",
  "Thabisile Tembe",
  "Thokozani Myeni",
  "Elias Mtethwa",
  "Methews Mtetwa",
  "James Sibiya",
  "Mandlenkosi Mntambo",
  "Skhumbuzo Mbuyazi",
  "Nkosingiphile Ndlovu",
  "Sihle Nsele",
  "Alson Mngomezulu",
  "S'Phumelele Mnguni",
  "Wellington Dlamini",
  "Sandile Shongwe",
  "Mandla Dlamini",
  "Snenhlahla Buthelezi",
  "Musawenkosi Manzini",
  "Vuyo Gumede",
  "Slindile Mlambo",
  "Lungisani Nkwanyana",
  "Simiso Sithole",
  "Bhekizitha Mthethwa",
  "Lungisani Phakati",
  "Nompumelelo Nkosi",
  "Sibusiso Mncwango",
  "Aaron Masinga",
  "Bongani Mhlongo",
  "Mduduzi Ndlazi",
  "Linda Mbatha",
  "Thabani Malinga",
  "Other",
] as const;