// Cintasign users (from Cinta.txt)
export const CINTASIGN_USERS = [
  "JASON WADE MENNELL",
  "NATALIE TAMRYN CROUCH",
  "RAEESA KADIR",
  "SBONGAMANDLA MNGUNI",
  "AYANDA MASIKANE",
  "MAWANDE MDUNJANA",
  "CORNE SCHALK DORFLING",
  "MBUSO MNGUNI",
  "JOHN DLAMINI",
  "SBONGESENI LUCKY NKOSI",
  "MUSAWENKOSI MYENI",
  "KHEDASI PATRICK MLAMBO",
  "SIYABONGA KHUMALO",
  "DUMEZWENI MBELE",
  "LINDANI DUBE",
  "SONOSAKHE NGUBANE",
  "SIFISO MCHUNU",
  "BONGIWE NKOMO",
  "BONG'MUSA NGUBO",
  "SIZWE MKHIZE",
  "RICHARD MKWAE",
  "SIYABONGA SPHAMANDLA NTSELE",
  "SIGWATA JOHN YENDE",
  "MXOLISI EMMANUEL SIBISI",
  "SAMSON MBONGENI NGWENYA",
  "SAMSON NDLOVU",
  "LUNGISANI PIUS MDLADLA",
  "THUBALETHIU SIMON MATHENJWA",
  "BHEKI - DINGUMUZI MKHUMBUZI",
  "MDUDUZI ERIC PHUNGULA",
  "NKOSINATHI THONGO BHENGU",
  "GUGU PRINCESS MTOLO",
  "MBUYISWA EMMANUEL NDLOVU",
  "BUSISIWE GOODNESS KUNENE",
  "THULANI ISAAC THOMO",
  "PHUMLANI SIPHO MAKHAYE",
  "TREVOR FANOZI MAGAGULA",
  "MDUDUZI WILLIAM NXUMALO",
  "THULANI TERRANCE MTHETHWA",
  "BONGANI BHENGU",
  "NOMUSA MARY-JANE BUTHELEZI",
  "SABELO GWEBU",
  "LONDIWE HADEBE",
  "SBUSISO WISEMAN KHOZA",
  "NKOSINATHI MICHAEL MKHONTO",
  "NKOSIPHANA AMEN MNGADI",
  "ZODWA NGCOBO",
  "ANDILE CYRIL NDLOVU",
  "MDUDUZI SITHOLE",
  "MZWAKHE GIFT NDWANDWE",
  "S'BUSISO BLESSIING THWALA",
  "ZWELIHLE NGEMA",
  "PHIWAYINKOSI ZAKHELE MTHEMBU",
  "BONGANI DESMOND MOTSOUNYANE",
  "BHEKIZENZO JOHANNES ZONDI",
  "LUCAS SIBUSISO MATHONSI",
  "NHLANHALA LINDA",
  "SONNYBOY MKHALIPHI",
  "SIKELELA JERMIA MKHUMBUZA",
  "MLUNGISI PETROS MAHLABA",
  "SABELO AYANDA VILANE",
  "MANDLA GIDION DLAMINI",
  "SKHUMBUZO KHUMBULANI MBUYAZI",
  "CLEMENT DLAMINI",
  "THOKOZANI MANDLA MYENI",
  "SIFISO REGGIE NENE"
] as const;

// Ringomode DSP users (from DSP users.txt)
export const RINGOMODE_USERS = [
  "Jason Wade Mennell",
  "Natalie Crouch",
  "Raeesa Kadir",
  "Sbongamandla Mnguni",
  "Ayanda Masikane",
  "Mawande Mdunjana",
  "Mbuso Mnguni",
  "Samson Ndlovu",
  "John Dlamini",
  "Sbongeseni Lucky Nkosi",
  "Musawenkosi Myeni",
  "Khedasi Patrick Mlambo",
  "Siyabonga Khumalo",
  "Dumezweni Mbele",
  "Wezile Matha Dlamini",
  "Lindani Dube",
  "Sonosakhe Ngubane",
  "Sifiso Mchunu",
  "Philani Mkhize",
  "Bongiwe Nkomo",
  "Bongimusa Ngubo",
  "Sizwe Mkhize",
  "Siyabonga Sphamandla Ntsele",
  "Sigwata John Yende",
  "Mxolisi Emmanuel Sibisi",
  "Samson Mbongeni Ngwenya",
  "Lungisani Pius Mdladla",
  "Thubalethiu Simon Mathenjwa",
  "Bheki Dingumuzi Mkhumbuzi",
  "Mduduzi Eric Phungula",
  "Nkosinathi Thongo Bhengu",
  "Ayanda Dlamini",
  "Goodwill Ngcobo",
  "Sabelo Cyprian Maseko",
  "Nkosinathi Innocent Zondi",
  "Gugu Princess Mtolo",
  "Mbuyiswa Emmanuel Ndlovu",
  "Bongani Bhuqo Dumakude",
  "Sithembiso Siboniso Mtshali",
  "Busisiwe Goodness Kunene",
  "Thulani Isaac Thomo",
  "Phumlani Sipho Makhaye",
  "Trevor Fanozi Magagula",
  "Mduduzi William Nxumalo",
  "Thulani Terrance Mthethwa",
  "Bongani Bhengu",
  "Nomusa Mary-Jane Buthelezi",
  "Sabelo Gwebu",
  "Londiwe Hadebe",
  "Sbusiso Khoza",
  "Michael Mkhonto",
  "Nkosiphana Amen Mngadi",
  "Zodwa Ngcobo",
  "Andile Cyril Ndlovu",
  "Mduduzi Sithole",
  "Mzwakhe Gift Ndwandwe",
  "Moses Ndeni Cebekhulu",
  "S'busiso Thwala",
  "Simanga Alson Makhanya",
  "Zwelihle Ngema",
  "Ntozakhe Simon Hlophe",
  "Phiwayinkosi Zakhele Mthembu",
  "Bongani Desmond Motsounyane",
  "Bhekizenzo Johannes Zondi",
  "Lucas Sibusiso Mathonsi",
  "Mfanzile Elphaus Magagula",
  "Nhlanhala Linda",
  "Sonnyboy Mkhaliphi",
  "Mzwahkhe Kenneth Manyoni",
  "Sikelela Jermia Mkhumbuza",
  "Nithesh Govender",
  "Barbara Smith",
  "Brett Darren Swart",
  "Wiseman Phumlani Ngcobo",
  "Jacho Neethling",
  "Emmanuel Nkosikhona Zulu",
  "Ian Rosselloty",
  "Michael John Shuttleworth",
  "Charl Nicholas Donelly",
  "Sbonelo Mngusi Gwamanda",
  "Braxton Moodley",
  "Other",
  "MLUNGISI PETROS MAHLABA",
  "SABELO AYANDA VILANE",
  "MANDLA GIDION DLAMINI",
  "SKHUMBUZO KHUMBULANI MBUYAZI",
  "CLEMENT DLAMINI",
  "THOKOZANI MANDLA MYENI",
  "SIFISO REGGIE NENE",
  "SBONGISENI ZULU",
  "ADRIAN DOMINIC BUCKLEY",
  "PETROS BONGINKOSI MOLEFE",
  "SITEMBISO VICTOR BHENGU",
  "ZAMANI LINDOKHULE NGUBO"
] as const;