// scripts/seed-forms.ts
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY! // use service role key for admin access
);

const forms = [
  {
    form_type: 'light-delivery',
    title: 'Light Delivery Vehicle',
    subtitle: 'Daily Checklist',
    description: 'Pre-trip inspection for light delivery vehicles including checks for tyres, brakes, lights, and safety equipment.',
    document_ref: 'HSEMS/8.1.19/REG/012',
    item_count: 26,
    icon_name: 'Truck',
    is_active: true,
  },
  {
    form_type: 'excavator-loader',
    title: 'Excavator Loader',
    subtitle: 'Pre-Shift Inspection',
    description: 'Comprehensive pre-shift inspection for excavator loaders covering hydraulics, tracks, controls, and safety systems.',
    document_ref: 'HSEMS/8.1.19/REG/002',
    item_count: 33,
    icon_name: 'Tractor',
    is_active: true,
  },
  {
    form_type: 'excavator-harvester',
    title: 'Excavator Harvester',
    subtitle: 'Pre-Shift Inspection',
    description: 'Pre-shift inspection for excavator harvesters including harvester head, feed rollers, delimbing knives, and safety checks.',
    document_ref: 'HSEMS/8.1.19/REG/001',
    item_count: 36,
    icon_name: 'TreePine',
    is_active: true,
  },
  {
    form_type: 'lowbed-trailer',
    title: 'Lowbed & Roll Back Trailer',
    subtitle: 'Pre-Shift Inspection',
    description: 'Complete inspection for lowbed and roll back trailers including deck condition, hydraulics, winch, tyres, and coupling systems.',
    document_ref: 'HSEMS/8.1.19/REG/020',
    item_count: 29,
    icon_name: 'Container',
    is_active: true,
  },
  {
    form_type: 'lowbed-stepdeck-trailer',
    title: 'Lowbed And Step Deck Trailer',
    subtitle: 'Pre-Use Inspection',
    description: 'Pre-use inspection for lowbed and step deck trailers covering deck, tow bar, landing gear, anchor points, and safety equipment.',
    document_ref: 'HSEMS/8.1.19/REG/021',
    item_count: 26,
    icon_name: 'Container',
    is_active: true,
  },
  {
    form_type: 'mechanic-ldv',
    title: 'Mechanic LDV',
    subtitle: 'Daily Checklist',
    description: 'Specialized daily inspection for mechanic light delivery vehicles covering tools, equipment, and vehicle systems.',
    document_ref: 'HSEMS/8.1.19/REG/017',
    item_count: 24,
    icon_name: 'Wrench',
    is_active: true,
  },
  {
    form_type: 'personal-labour-carrier',
    title: 'Personal / Labour Carrier',
    subtitle: 'Inspection Checklist',
    description: 'Daily inspection for personnel carriers including safety equipment, tyres, brakes, and passenger area.',
    document_ref: 'HSEMS/8.1.19/REG/011',
    item_count: 20,
    icon_name: 'Bus',
    is_active: true,
  },
  {
    form_type: 'ponsse-bison',
    title: 'Ponsse Bison',
    subtitle: 'Pre-Shift Inspection',
    description: 'Complete pre-shift inspection for the Ponsse Bison harvester including boom structure, hydraulics, grab, and safety systems.',
    document_ref: 'HSEMS/8.1.19/REG/022',
    item_count: 34,
    icon_name: 'Combine',
    is_active: true,
  },
  {
    form_type: 'self-loading-forwarder',
    title: 'Self Loading Forwarder',
    subtitle: 'Pre-Shift Inspection',
    description: 'Pre-shift inspection for self‑loading forwarders covering boom, hydraulics, grab, tyres, and safety systems.',
    document_ref: 'HSEMS/8.1.19/REG/003',
    item_count: 32,
    icon_name: 'Tractor',
    is_active: true,
  },
  {
    form_type: 'skidder',
    title: 'Skidder (Grapple & Cable)',
    subtitle: 'Pre-Shift Inspection',
    description: 'Pre-shift inspection for skidders including grapple, cable, winch, hydraulics, and safety systems.',
    document_ref: 'HSEMS/8.1.19/REG/006',
    item_count: 28,
    icon_name: 'Logs',
    is_active: true,
  },
  {
    form_type: 'timber-truck-trailer',
    title: 'Timber Truck And Trailer',
    subtitle: 'Checklist',
    description: 'Complete inspection for timber trucks and trailers covering brakes, lights, tyres, and fire extinguisher.',
    document_ref: 'HSEMS/8.1.19/REG/010',
    item_count: 24,
    icon_name: 'Truck',
    is_active: true,
  },
  {
    form_type: 'trailer',
    title: 'Trailer (Excluding Labour)',
    subtitle: 'Inspection Checklist',
    description: 'Trailer inspection covering body, lights, brakes, tyres, and safety equipment.',
    document_ref: 'HSEMS/4.4.6.19/REG/013',
    item_count: 15,
    icon_name: 'Container',
    is_active: true,
  },
  {
    form_type: 'service-diesel-truck',
    title: 'Service/Diesel Truck',
    subtitle: 'Pre-Shift Inspection',
    description: 'Pre-shift inspection for service/diesel trucks including engine, brakes, lights, and fluid levels.',
    document_ref: 'HSEMS/8.1.19/REG/???',
    item_count: 23,
    icon_name: 'Fuel',
    is_active: true,
  },
  {
    form_type: 'vehicle-job-card',
    title: 'Motorised Equipment/Vehicle Job Card',
    subtitle: 'Work Order',
    description: 'Job card for recording repairs, maintenance, and tests on equipment and vehicles.',
    document_ref: 'HSEMS/8.1.19/REG/???',
    item_count: 0,
    icon_name: 'FileText',
    is_active: true,
  },
  {
    form_type: 'water-cart-trailer',
    title: 'Water Cart Trailer & Pressure Washer',
    subtitle: 'Inspection Checklist',
    description: 'Daily inspection for water cart trailers and pressure washers covering lights, tyres, tank, hose, and engine.',
    document_ref: 'HSEMS/8.1.19/REG/015',
    item_count: 27,
    icon_name: 'Droplets',
    is_active: true,
  },
  {
    form_type: 'weekly-machinery-condition',
    title: 'Weekly Machinery Condition Assessment',
    subtitle: 'Weekly Assessment',
    description: 'Comprehensive weekly assessment of machinery condition covering engine, chassis, transmission, hydraulics, and attachments.',
    document_ref: 'HSEMS/8.1.19/DOC/011',
    item_count: 84,
    icon_name: 'ClipboardCheck',
    is_active: true,
  },
  {
    form_type: 'bell-timber-truck',
    title: 'Bell Timber Truck',
    subtitle: 'Pre-Shift Checklist',
    description: 'Pre-shift inspection for Bell timber trucks covering cab, hydraulics, brakes, boom, and safety equipment.',
    document_ref: 'HSEMS/8.1.19/REG/019',
    item_count: 43,
    icon_name: 'Combine',
    is_active: true,
  },
  {
    form_type: 'daily-attachment-checklist',
    title: 'Daily Attachment Checklist',
    subtitle: 'Daily Checklist',
    description: 'Daily inspection for harvester attachments including head, grab, and winch.',
    document_ref: 'HSEMS/8.1.19/REG/012',
    item_count: 39,
    icon_name: 'ClipboardList',
    is_active: true,
  },
  {
    form_type: 'daily-machine-checklist',
    title: 'Daily Machine Checklist',
    subtitle: 'Daily Checklist',
    description: 'Daily inspection for machines covering engine, chassis, hydraulics, and attachments.',
    document_ref: 'HSEMS/8.1.19/DOC/011',
    item_count: 84,
    icon_name: 'ClipboardCheck',
    is_active: true,
  },
  {
    form_type: 'dezzi-timber-truck',
    title: 'Dezzi Timber Truck',
    subtitle: 'Pre-Shift Checklist',
    description: 'Pre-shift inspection for Dezzi timber trucks covering cab, hydraulics, brakes, boom, and safety equipment.',
    document_ref: 'HSEMS/8.1.19/REG/004',
    item_count: 41,
    icon_name: 'Truck',
    is_active: true,
  },
  {
    form_type: 'diesel-cart-trailer',
    title: 'Diesel Cart Trailer',
    subtitle: 'Inspection Checklist',
    description: 'Inspection for diesel cart trailers covering tank, lights, brakes, tyres, and fire extinguisher.',
    document_ref: 'HSEMS/8.1.9/REG/014',
    item_count: 15,
    icon_name: 'Container',
    is_active: true,
  },
  {
    form_type: 'cintasign-harvesting',
    title: 'Cintasign Harvesting',
    subtitle: 'Daily Log',
    description: 'Record daily harvesting operations including fleet details, tree volumes, and breakdowns.',
    document_ref: 'CINT/HARV/001',
    item_count: 0,
    icon_name: 'TreePine',
    is_active: true,
  },
  {
    form_type: 'cintasign-shorthaul',
    title: 'Cintasign Shorthaul',
    subtitle: 'Daily Log',
    description: 'Record daily shorthaul operations including fleet details, loads, and breakdowns.',
    document_ref: 'CINT/LOG/001',
    item_count: 0,
    icon_name: 'Truck',
    is_active: true,
  },
  {
    form_type: 'cintasign-loading',
    title: 'Cintasign Loading',
    subtitle: 'Daily Log',
    description: 'Record daily loading operations including delivery notes, transport companies, and drivers.',
    document_ref: 'CINT/LOAD/001',
    item_count: 0,
    icon_name: 'Container',
    is_active: true,
  },
];

async function seed() {
  console.log('Seeding forms...');
  const { error } = await supabase.from('forms').insert(forms);
  if (error) {
    console.error('Error inserting forms:', error);
  } else {
    console.log('Forms inserted successfully!');
  }
}

seed();